-- V3__Create_scheduled_jobs_table.sql
CREATE TABLE scheduled_jobs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    job_id VARCHAR(100) NOT NULL UNIQUE,
    job_name VARCHAR(255) NOT NULL,
    job_class_name VARCHAR(500) NOT NULL,
    job_type VARCHAR(50) NOT NULL,
    group_key VARCHAR(100),
    can_group BOOLEAN NOT NULL DEFAULT FALSE,
    group_buffer_millis BIGINT,
    interval_millis BIGINT,
    initial_delay_millis BIGINT,
    repetition_type VARCHAR(50),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    execution_time_ms BIGINT,
    error_message TEXT,
    retry_count INT NOT NULL DEFAULT 0,
    max_retries INT NOT NULL DEFAULT 3,
    priority INT NOT NULL DEFAULT 5,
    metadata TEXT,
    thread_pool_id BIGINT,
    app_server_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (thread_pool_id) REFERENCES thread_pools(id) ON DELETE SET NULL,
    FOREIGN KEY (app_server_id) REFERENCES app_servers(id) ON DELETE SET NULL,
    
    INDEX idx_scheduled_jobs_job_id (job_id),
    INDEX idx_scheduled_jobs_status (status),
    INDEX idx_scheduled_jobs_job_type (job_type),
    INDEX idx_scheduled_jobs_status_type (status, job_type),
    INDEX idx_scheduled_jobs_group_key (group_key),
    INDEX idx_scheduled_jobs_group_status (group_key, status),
    INDEX idx_scheduled_jobs_thread_pool (thread_pool_id),
    INDEX idx_scheduled_jobs_app_server (app_server_id),
    INDEX idx_scheduled_jobs_submitted_at (submitted_at),
    INDEX idx_scheduled_jobs_started_at (started_at),
    INDEX idx_scheduled_jobs_completed_at (completed_at),
    INDEX idx_scheduled_jobs_priority (priority),
    INDEX idx_scheduled_jobs_retry_count (retry_count),
    INDEX idx_scheduled_jobs_execution_time (execution_time_ms),
    INDEX idx_scheduled_jobs_submitted_today (submitted_at),
    INDEX idx_scheduled_jobs_completed_today (completed_at)
);

